### ISSUE TITLE
jquery-wechat 访问目录在哪？

### ISSUE THREAD

**Issue by honger05** [leftstick/leftstick.github.com#1]
Hi, leftstick.

请教一个问题

我使用的是 jekyll， 访问我自己的静态 html ，通常是这样的方式

比如

``` js
http://leftstick.github.io/jquery-wechat/index.html
```

然后 index.html 是放在 jquery-wechat  目录里的。

``` js
http://leftstick.github.io/jquery-wechat/
```

 /jquery-wechat/ 这个是怎么加上去的 ？

也没看到你  repository 中有这个目录，因此也不是我那种方式。

**Comment by leftstick** [comment]
`github pages` 服务分两种：
1. for User or Organization
2. for Project

依照你说的情况，我猜你应该是想为项目做一个文档介绍页面之类的东西？如果是，你得先看：[pages-github](https://pages.github.com/)攻略，选择`Project site` 如下：
![snip20150929_1](https://cloud.githubusercontent.com/assets/1059956/10166675/b204b5e4-66f7-11e5-8a9f-fb1d3480401a.png)

按文档做就可以了。`jekyll`的工作原理是，会按照一定的规范将源码"编译"，然后生成静态网站文件到`_site`目录下，具体知识点你可以在[jekyll-官网](http://jekyllrb.com/docs/home/)找到

**Comment by honger05** [comment]
万分感谢...  过会儿去看看
